### ISSUE TITLE
Spaces double encoded

### ISSUE THREAD

**Issue by ludwiktrammer** [alrusdi/jquery-plugin-query-object#10]
When the `spaces` option is set to `true` the `toString` method changes spaces to "+" signs and then urlencodes the "+"  sign again, making it a literal "+" instead of encoded space:

    if ($spaces) str = str.replace(/ /g, "+");
    return encodeURIComponent(str);

The first line changes spaces to `+`, the second line changes `+` to `%2B`.

**Comment by alrusdi** [comment]
Seems to be fixed
