### ISSUE TITLE
Hash params get converted to query params

### ISSUE THREAD

**Issue by lolmaus** [alrusdi/jquery-plugin-query-object#13]
### Steps to reproduce

Given URL `http://example.com#foo`, evaluate `$.query.set('bar', true).toString()`.

### Expected return value

    ?bar#foo

### Actual return value

    ?bar&foo

A hash param gets converted to query param. It's impossible to use `jquery-plugin-query-object` if both query and hash params are present.

**Comment by alrusdi** [comment]
Yes, with this library you can use only hash params or search, not both.
I will not fix it to not break backward compatibility
Use https://github.com/medialize/URI.js instead of jquery-plugin-query-object for more advanced cases
