### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by yagebu** [alrusdi/jquery-plugin-query-object#15]
Hey thank you very much for this nice jQuery plugin!

The bug that was fixed in #11 makes it unusable for me, so it would be great if you could release a new version and publish it to `npm`.

It would be nice if my project could depend on a released version, and I think the fix warrants a new release :)

**Comment by alrusdi** [comment]
Version 2.2.3 released

**Comment by yagebu** [comment]
Perfect! Thank you :)
