### ISSUE TITLE
Uncomplete documentation

### ISSUE THREAD

**Issue by aiphee** [alrusdi/jquery-plugin-query-object#16]
Hi, this plugin suits my needs excellently, no other plugin was so easily able to read and write nested data. 

What im missing is better documentation, for example what is the difference between `parseNew` and `load`? Thank you. 

I could try to improve README a little if you are accepting pull requests.

**Comment by alrusdi** [comment]
Feel free to improve the docs. I like pull requests very much) https://github.com/alrusdi/jquery-plugin-query-object/pulls?q=is%3Apr+is%3Aclosed

**Comment by aiphee** [comment]
And difference between parseNew and load is that parseNew rewrites current object and load returns new object right?
