### ISSUE TITLE
$.query.get does not take into account changes to history

### ISSUE THREAD

**Issue by Garrett-R** [alrusdi/jquery-plugin-query-object#17]
In HTML5, you can change the history with `window.history.pushState`, but this plugin doesn't recognize a changed history state.

Here's a minimal example:

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
<title>My Page</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://rawgit.com/alrusdi/jquery-plugin-query-object/master/jquery.query-object.js"></script>
</head>

<body>


<script>
var newURL = window.location.protocol + "//" + window.location.host + window.location.pathname 
             + $.query.set('current', 5).toString();
window.history.pushState(null, null, newURL)

console.log(window.location.href)
console.log($.query.get('current'))

</script>

</body>

</html>
```

If you run this (I ran it using Python's `python3 -m http.server` and opened it in Firefox), the console output is:

![image](https://cloud.githubusercontent.com/assets/6614695/13906928/bf255000-ee9f-11e5-84f7-7723d3c1a3e8.png)

I also tested on Chromium with the same result.

**Comment by alrusdi** [comment]
Dud you checked usage variants in docs:

In case you dynamically change document.location via history API

var parsedQuery = $.query.parseNew("?foo=bar", "bar=foo");
?foo=bar&bar=foo

In case you are using History.js

var parsedQuery = $.query.parseNew(location.search, location.hash.split("?").length > 1 ? location.hash.split("?")[1] : "");

**Comment by Garrett-R** [comment]
Oh whoops, thanks for the explanation!
