### ISSUE TITLE
Doesn't work with `window.history.pushState`

### ISSUE THREAD

**Issue by Garrett-R** [alrusdi/jquery-plugin-query-object#20]
I would expect that this plugin was aware of the URL _after_ I use `pushState`, but that's not the case.

For example,

```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://rawgit.com/alrusdi/jquery-plugin-query-object/master/jquery.query-object.js"></script>
</head>


<body>

<script>
window.history.pushState(null, '', location.href + '?q=hello');
document.write('q equals: ' + $.query.get('q'));
</script>

</body>
</html>
```

output just `q equals:`.

**Comment by rdarin** [comment]
FYI - if you update the code to the following (from the readme) it should work:
`
window.history.pushState(null, '', location.href + '?q=hello');
var parsedQuery = $.query.parseNew(location.search, location.hash.split("?").length > 1 ? location.hash.split("?")[1] : "");
document.write('q equals: ' + $.query.get('q'));
`

Obviously not ideal, but it does the job.

**Comment by alrusdi** [comment]
Good to have workaround
