### ISSUE TITLE
Parse custom string, without modifying query

### ISSUE THREAD

**Issue by esemlabel** [alrusdi/jquery-plugin-query-object#21]
Is it possible to $.query.parseNew('some=string&with=parameters) without modifying main query? For example, to get some values for additional use, that are in some string and not in URL.
Thank you!

**Comment by alrusdi** [comment]
No, it's not recomended workflow for this plugin.
You can use https://github.com/medialize/URI.js project - it is excelent replacement for jquery-plugin-query-object
