### ISSUE TITLE
parameter capitalization problem.

### ISSUE THREAD

**Issue by lvcao20** [alrusdi/jquery-plugin-query-object#23]
url: http://aaa.com?defaultUrl=1234

1. $.query.get("defaulturl")   ---> ""
2. $.query.get("defaultUrl")  ---> "1234"

i want to get the current result with case 1, what can i do?

**Comment by alrusdi** [comment]
This problem is out of scope of jquery-plugin-query-object.
I recommend you to use URI.js if its suits your need
