### ISSUE TITLE
Script drops leading 0

### ISSUE THREAD

**Issue by zwick** [alrusdi/jquery-plugin-query-object#8]
When there is a number in the URL parameters that has a leading 0 (such as a zipcode), the 0 is dropped when using your jQuery plugin to append more values to the URL.

We were able to fix this with the following change to line 99:

Original:
else if (/^[+-]?[0-9]+$/.test(val)) // simple int regex

New:
else if (/^[+-]?[1-9][0-9]*$/.test(val)) // simple int regex 

Thought I would share this in case anyone else has this similar issue.  Not sure if it is a perfect solution, but it does now maintain the value.

**Comment by alrusdi** [comment]
Your code is merged into script. Thank you!

**Comment by zwick** [comment]
I'm glad I could contribute :) 

Thank you for the nice jquery plugin!
