### ISSUE TITLE
Syntax error in example code

### ISSUE THREAD

**Issue by ludwiktrammer** [alrusdi/jquery-plugin-query-object#9]
This is a code from documentation:

    <script type="text/javascript">
    var jQuery.query = { numbers: false, hash: true };
    </script>

it causes an `Uncaught SyntaxError: Unexpected token .` error. The issue is `var` - it shouldn't be there, since we are setting a property on the jQuery, not creating a new variable. This may be trivial, but it took me couple of minutes before I noticed the source of the problem.

**Comment by alrusdi** [comment]
Thank you! I've corrected the docs.
